---

- name: Install python package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  register: install_python_package_dependencies
  with_items: "{{ _python_package_dependencies | default([]) }}"
  when:
    - _python_package_dependencies is defined
    - python_pyenv_install
  tags:
    - dependences
